# Generated by Django 4.1.3 on 2023-01-07 16:42

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='description',
            field=tinymce.models.HTMLField(default='course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
