# Generated by Django 4.1.3 on 2023-01-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_courses_description_courses_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='image',
            field=models.FileField(default='a', upload_to='frontend/src/images/courses'),
            preserve_default=False,
        ),
    ]
