# Generated by Django 4.1.5 on 2023-01-31 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_courses_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='rate',
        ),
        migrations.AddField(
            model_name='courses',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
