# Generated by Django 4.1.3 on 2023-01-23 04:07

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('body', tinymce.models.HTMLField()),
                ('image', models.ImageField(upload_to='frontend/public/images/blog')),
                ('description', tinymce.models.HTMLField()),
                ('time', models.DateField()),
            ],
        ),
    ]
