# Generated by Django 4.1.3 on 2023-01-21 17:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_election_participant_alter_election_candidates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votes',
            old_name='tovote',
            new_name='voter',
        ),
        migrations.RemoveField(
            model_name='votes',
            name='elections',
        ),
        migrations.AddField(
            model_name='votes',
            name='votes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
