# Generated by Django 4.1.3 on 2023-01-22 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_votes_elections_alter_votes_voter'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='field_of_Study',
            field=models.IntegerField(choices=[(1, 'برق صنعتی'), (2, 'تأسیسات الکتریکی'), (3, 'فناوری اطلاعات و ارتباطات'), (4, 'الکترونیک'), (5, 'نرم\u200cافزار کامپیوتر'), (6, 'ساختمان'), (7, 'نقشه برداری'), (8, 'معماری'), (9, 'حسابداری'), (10, 'تبلیغات و بازاریابی'), (11, 'صنایع فلزی - جوشکاری'), (12, 'طراحی صنعتی')], default=1),
            preserve_default=False,
        ),
    ]
